name: "Install Project"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.7

    # "-0" allows invalidating the cache for upgrading Poetry
    - uses: actions/cache@v2
      with:
        path: ~/.local
        key: poetry-1.2.2-0

    # `virtualenvs-in-project: true` creates a `.venv` in test dir for easy caching
    - uses: snok/install-poetry@v1
      with:
        version: 1.2.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - id: cache-deps
      uses: actions/cache@v2
      with:
        path: .venv
        key: pydeps-${{ hashFiles('**/poetry.lock') }}

    - run: poetry install --no-interaction --with ci --no-root
      shell: bash
      if: steps.cache-deps.outputs.cache-hit != 'true'
    - run: poetry install --no-interaction --with ci
      shell: bash
