on: push

jobs:
  # Run PyTest
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: poetry run pytest
        env:
          PGPORT: 5432
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres

  # Publish to PyPI
  publish:
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - shell: bash
        run: |
          scripts/cd-publish.sh
        env:
          PYPI_USER: __token__
          PYPI_PASS: ${{ secrets.PYPI_TOKEN }}
