on: push

jobs:
  ci-flow:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.7

      # "-0" allows invalidating the cache for upgrading Poetry
      - uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.2.2-0

      # `virtualenvs-in-project: true` creates a `.venv` in test dir for easy caching
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install --no-interaction --with ci --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: poetry install --no-interaction --with ci

      - run: poetry shell && pytest
        env:
          PGPORT: 5432
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
        
      #  TODO: generate appropriately scoped access token so a bot can comment lint results
      # - run: |
      #     mypy src --show-error-codes --show-error-context --pretty && \
      #     black src --check && \
      #     isort "src"/**/*.py -m 3 --trailing-comma -c && \
      #     pylint src --exit-zero

      - run: |
          sphinx-apidoc -q -f -o docs/api src/pg4n '*/test_*' && \
          sphinx-build -q -b html docs docs/build && \
          touch docs/build/.nojekyll
        if: github.ref == 'refs/heads/feat/add-docs'
      - uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/feat/add-docs'
        with:
          folder: docs/build
          git-config-name: github-actions
          git-config-email: <>
