on: pull_request

jobs:
  pr_flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - shell: bash
        run: |
          scripts/ci-grade.sh > grade.txt
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_SECRET }}
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: grade.txt
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_SECRET }}
