on: pull_request

jobs:
  pr_flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - shell: bash
        run: |
          echo 'GRADE<<EOF' >> $GITHUB_ENV
          poetry run scripts/ci-grade.sh >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ```
            ${{ env.GRADE }}
            ```
          comment_includes: '```'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_SECRET }}
