on: push

jobs:
  push_flow:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: poetry run pytest
        env:
          PGPORT: 5432
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres

      - run: |
          poetry run sphinx-apidoc -q -f -o docs/api src/pg4n '*/test*' && \
          poetry run sphinx-build -q -b html docs docs/build && \
          touch docs/build/.nojekyll
        if: github.ref == 'refs/heads/main'

      - uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.BOT_SECRET }}
          repository-name: Project-C-SQL/Project-C-SQL.github.io
          folder: docs/build
          git-config-name: github-actions
          git-config-email: <>
